// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-sessions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect with your Visual Astro account." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-sessions.ts
var list_sessions_default = defineTool({
  name: "list_sessions",
  title: "List observing sessions",
  description: "List the signed-in observer's visual observing sessions, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of sessions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").select("id,name,observed_at_utc,jd,notes,is_favorite").order("observed_at_utc", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-observations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_observations_default = defineTool2({
  name: "list_observations",
  title: "List observations",
  description: "List observations for one session (or the most recent ones across all sessions) with star name, comparison stars, steps, limit and UT time.",
  inputSchema: {
    session_id: z2.string().uuid().optional().describe("Session id to read; omit to read the latest observations."),
    limit: z2.number().int().min(1).max(500).default(100).describe("Maximum number of observations to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("observations").select("id,session_id,row_index,ut_time,a,b,pasos_a,pasos_b,limit_value,note,stars(name,constellation)").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (session_id) query = query.eq("session_id", session_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { observations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-stars.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_stars_default = defineTool3({
  name: "list_stars",
  title: "List catalog stars",
  description: "List the observer's visual star catalog, optionally filtered by constellation or a name search.",
  inputSchema: {
    constellation: z3.string().trim().min(1).optional().describe("Filter by constellation code, e.g. 'Dra'."),
    search: z3.string().trim().min(1).optional().describe("Case-insensitive star name search."),
    limit: z3.number().int().min(1).max(500).default(200).describe("Maximum number of stars to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ constellation, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("stars").select("id,name,constellation,type,aavso_code,vsnet_code,chart_id,notes,sort_order").order("constellation").order("sort_order").limit(limit ?? 200);
    if (constellation) query = query.eq("constellation", constellation);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { stars: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-ccd-targets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_ccd_targets_default = defineTool4({
  name: "list_ccd_targets",
  title: "List POZOR CCD targets",
  description: "List the observer's CCD/photometry targets with coordinates, epoch and period.",
  inputSchema: {
    search: z4.string().trim().min(1).optional().describe("Case-insensitive target name search."),
    limit: z4.number().int().min(1).max(500).default(200).describe("Maximum number of targets to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("ccd_targets").select("id,name,constellation,ra_hours,dec_deg,epoch_jd,period_days,filters,notes,sort_order").order("constellation").order("sort_order").limit(limit ?? 200);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { targets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-session.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_session_default = defineTool5({
  name: "create_session",
  title: "Create observing session",
  description: "Create a new visual observing session for the signed-in observer.",
  inputSchema: {
    name: z5.string().trim().min(1).max(200).optional().describe("Session name."),
    observed_at_utc: z5.string().trim().optional().describe("Observation date/time in UTC ISO format; defaults to now."),
    notes: z5.string().trim().max(2e3).optional().describe("Free-form session notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, observed_at_utc, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").insert({
      user_id: ctx.getUserId(),
      name: name ?? null,
      notes: notes ?? null,
      ...observed_at_utc ? { observed_at_utc } : {}
    }).select("id,name,observed_at_utc,notes").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tbmyxbratepxomskzzsq";
var mcp_default = defineMcp({
  name: "visual-astro",
  title: "Visual Astro",
  version: "0.1.0",
  instructions: "Tools for Visual Astro, a variable-star observing logbook. Read observing sessions and their observations, browse the visual star catalog and POZOR CCD targets, and create new sessions. All data is scoped to the signed-in observer.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_sessions_default, list_observations_default, list_stars_default, list_ccd_targets_default, create_session_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
