// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-sessions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect with your Visual Astro account." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-sessions.ts
var list_sessions_default = defineTool({
  name: "list_sessions",
  title: "List observing sessions",
  description: "List the signed-in observer's visual observing sessions, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of sessions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").select("id,name,observed_at_utc,jd,notes,is_favorite").order("observed_at_utc", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-observations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_observations_default = defineTool2({
  name: "list_observations",
  title: "List observations",
  description: "List observations for one session (or the most recent ones across all sessions) with star name, comparison stars, steps, limit and UT time.",
  inputSchema: {
    session_id: z2.string().uuid().optional().describe("Session id to read; omit to read the latest observations."),
    limit: z2.number().int().min(1).max(500).default(100).describe("Maximum number of observations to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("observations").select("id,session_id,row_index,ut_time,a,b,pasos_a,pasos_b,limit_value,note,stars(name,constellation)").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (session_id) query = query.eq("session_id", session_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { observations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-stars.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_stars_default = defineTool3({
  name: "list_stars",
  title: "List catalog stars",
  description: "List the observer's visual star catalog, optionally filtered by constellation or a name search.",
  inputSchema: {
    constellation: z3.string().trim().min(1).optional().describe("Filter by constellation code, e.g. 'Dra'."),
    search: z3.string().trim().min(1).optional().describe("Case-insensitive star name search."),
    limit: z3.number().int().min(1).max(500).default(200).describe("Maximum number of stars to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ constellation, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("stars").select("id,name,constellation,type,aavso_code,vsnet_code,chart_id,notes,sort_order").order("constellation").order("sort_order").limit(limit ?? 200);
    if (constellation) query = query.eq("constellation", constellation);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { stars: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-ccd-targets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_ccd_targets_default = defineTool4({
  name: "list_ccd_targets",
  title: "List POZOR CCD targets",
  description: "List the observer's CCD/photometry targets with coordinates, epoch and period.",
  inputSchema: {
    search: z4.string().trim().min(1).optional().describe("Case-insensitive target name search."),
    limit: z4.number().int().min(1).max(500).default(200).describe("Maximum number of targets to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("ccd_targets").select("id,name,constellation,ra_hours,dec_deg,epoch_jd,period_days,filters,notes,sort_order").order("constellation").order("sort_order").limit(limit ?? 200);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { targets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-session.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_session_default = defineTool5({
  name: "create_session",
  title: "Create observing session",
  description: "Create a new visual observing session for the signed-in observer.",
  inputSchema: {
    name: z5.string().trim().min(1).max(200).optional().describe("Session name."),
    observed_at_utc: z5.string().trim().optional().describe("Observation date/time in UTC ISO format; defaults to now."),
    notes: z5.string().trim().max(2e3).optional().describe("Free-form session notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, observed_at_utc, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").insert({
      user_id: ctx.getUserId(),
      name: name ?? null,
      notes: notes ?? null,
      ...observed_at_utc ? { observed_at_utc } : {}
    }).select("id,name,observed_at_utc,notes").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/tools/get-session.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";

// src/lib/pozor.ts
import * as Astronomy from "npm:astronomy-engine@^2.1.19";

// src/lib/promStore.ts
import bundled from "npm:@/data/prom.json";
var KEY = "prom_overrides_v1";
function readOverrides() {
  if (typeof window === "undefined") return {};
  try {
    const raw = localStorage.getItem(KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}
function getPromTable() {
  const ov = readOverrides();
  const out = {};
  for (const [name, letters] of Object.entries(bundled)) {
    if (name in ov) continue;
    out[name] = { ...letters };
  }
  for (const [name, letters] of Object.entries(ov)) {
    if (letters && Object.keys(letters).length === 0 && !(name in bundled)) continue;
    if (letters && Object.keys(letters).length === 0) continue;
    out[name] = { ...letters };
  }
  return out;
}
function getPromStar(name) {
  return getPromTable()[name];
}

// src/lib/astro.ts
function dateToJD(d) {
  const year = d.getUTCFullYear();
  const month = d.getUTCMonth() + 1;
  const day = d.getUTCDate() + (d.getUTCHours() + d.getUTCMinutes() / 60 + d.getUTCSeconds() / 3600) / 24;
  let Y = year;
  let M = month;
  if (M <= 2) {
    Y -= 1;
    M += 12;
  }
  const A = Math.floor(Y / 100);
  const B = 2 - A + Math.floor(A / 4);
  return Math.floor(365.25 * (Y + 4716)) + Math.floor(30.6001 * (M + 1)) + day + B - 1524.5;
}
function vsnetDate(d) {
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = d.getUTCDate();
  const frac = (d.getUTCHours() + d.getUTCMinutes() / 60 + d.getUTCSeconds() / 3600) / 24;
  const dayWithFrac = (day + frac).toFixed(3).padStart(6, "0");
  return `${y}${m}${dayWithFrac}`;
}
function meduzaDate(d) {
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = d.getUTCDate();
  const frac = (d.getUTCHours() + d.getUTCMinutes() / 60 + d.getUTCSeconds() / 3600) / 24;
  const dayWithFrac = (day + frac).toFixed(3).padStart(6, "0");
  return `${y}-${m}-${dayWithFrac}`;
}
function resolveCompValue(starName, raw) {
  if (raw == null) return NaN;
  const s = String(raw).trim();
  if (!s) return NaN;
  const direct = parseFloat(s);
  if (Number.isFinite(direct) && /^-?\d/.test(s)) return direct;
  if (!starName) return NaN;
  const tbl = getPromStar(starName);
  if (!tbl) return NaN;
  const v = tbl[s.toLowerCase()];
  return typeof v === "number" ? v : NaN;
}
function computeMagnitude(o, starName) {
  if (o.limit_value && o.limit_value.trim()) {
    return { value: o.limit_value.trim(), numeric: null };
  }
  const aNum = resolveCompValue(starName, o.a ?? null);
  const bNum = resolveCompValue(starName, o.b ?? null);
  const pa = o.pasos_a ?? null;
  const pb = o.pasos_b ?? null;
  if (Number.isFinite(aNum) && Number.isFinite(bNum) && pa !== null && pb !== null && pa + pb > 0) {
    const mag = aNum + pa / (pa + pb) * (bNum - aNum);
    return { value: mag.toFixed(2), numeric: mag };
  }
  return { value: null, numeric: null };
}
function applyUtTimeToDate(d, utTime) {
  if (!utTime) return;
  const m = /^(\d{1,2})[:.\s]+(\d{1,2})/.exec(String(utTime).trim());
  if (!m) return;
  const hh = parseInt(m[1], 10);
  const mm = parseInt(m[2], 10);
  d.setUTCHours(hh, mm, 0, 0);
  if (hh < 12) d.setUTCDate(d.getUTCDate() + 1);
}
function aavsoEstima(o) {
  if (o.limit_value && o.limit_value.trim()) return o.limit_value.trim();
  if (o.a && o.b && o.pasos_a !== null && o.pasos_b !== null) {
    return `${o.a}-${o.pasos_a}V${o.pasos_b}-${o.b}`;
  }
  return "";
}

// src/lib/pozor.ts
var AU_KM = 1495978707e-1;
var LIGHT_TIME_AU_SEC = 499.004784;
var POZOR_LOCATIONS = [
  { key: "piconcillo", label: "Piconcillo", lat: 38.181, lon: -5.4591, elevation: 0 },
  { key: "kolonica", label: "Kolonica", lat: 48.935, lon: 22.2739, elevation: 0 },
  { key: "hlohovec", label: "Hlohovec", lat: 48.4202, lon: 17.7969, elevation: 0 },
  { key: "madeira", label: "Madeira", lat: 32.689, lon: -17.0919, elevation: 0 }
];
var DEFAULT_MIN_ALTITUDE = 30;
function getLocation(key) {
  return POZOR_LOCATIONS.find((l) => l.key === key) ?? POZOR_LOCATIONS[0];
}
function observerOf(loc) {
  return new Astronomy.Observer(loc.lat, loc.lon, loc.elevation);
}
function formatHMS(hours) {
  let total = Math.round((hours % 24 + 24) % 24 * 3600);
  if (total >= 86400) total -= 86400;
  const h = Math.floor(total / 3600);
  const m = Math.floor((total - h * 3600) / 60);
  const s = total - h * 3600 - m * 60;
  return `${h}h${String(m).padStart(2, "0")}m${String(s).padStart(2, "0")}s`;
}
function formatDMS(deg) {
  const sign = deg < 0 ? "\u2212" : "+";
  const a = Math.abs(deg);
  let total = Math.round(a * 3600);
  const d = Math.floor(total / 3600);
  const m = Math.floor((total - d * 3600) / 60);
  const s = total - d * 3600 - m * 60;
  return `${sign}${d}\xB0${String(m).padStart(2, "0")}\u2032${String(s).padStart(2, "0")}\u2033`;
}
function utcDate(isoDate, utHours = 0) {
  const [y, m, d] = isoDate.split("-").map(Number);
  const ms = Math.round(utHours * 3600 * 1e3);
  return new Date(Date.UTC(y, (m ?? 1) - 1, d ?? 1, 0, 0, 0, 0) + ms);
}
function toIsoDate(d) {
  return d.toISOString().slice(0, 10);
}
function jdToDate(jd) {
  const z26 = Math.floor(jd + 0.5);
  const f = jd + 0.5 - z26;
  let a = z26;
  if (z26 >= 2299161) {
    const alpha = Math.floor((z26 - 186721625e-2) / 36524.25);
    a = z26 + 1 + alpha - Math.floor(alpha / 4);
  }
  const b = a + 1524;
  const c = Math.floor((b - 122.1) / 365.25);
  const d = Math.floor(365.25 * c);
  const e = Math.floor((b - d) / 30.6001);
  const dayF = b - d - Math.floor(30.6001 * e) + f;
  const day = Math.floor(dayF);
  const month = e < 14 ? e - 1 : e - 13;
  const year = month > 2 ? c - 4716 : c - 4715;
  const msOfDay = Math.round((dayF - day) * 86400 * 1e3);
  return new Date(Date.UTC(year, month - 1, day) + msOfDay);
}
function unitVector(raHours, decDeg) {
  const ra = raHours * 15 * Math.PI / 180;
  const dec = decDeg * Math.PI / 180;
  return [Math.cos(dec) * Math.cos(ra), Math.cos(dec) * Math.sin(ra), Math.sin(dec)];
}
function precessToDate(raHours, decDeg, date) {
  const time = Astronomy.MakeTime(date);
  const [x, y, z26] = unitVector(raHours, decDeg);
  const rot = Astronomy.Rotation_EQJ_EQD(time);
  const v = Astronomy.RotateVector(rot, new Astronomy.Vector(x, y, z26, time));
  const r = Math.hypot(v.x, v.y, v.z);
  const ra = Math.atan2(v.y, v.x) * 180 / Math.PI / 15;
  const dec = Math.asin(v.z / r) * 180 / Math.PI;
  return { raHours: (ra % 24 + 24) % 24, decDeg: dec };
}
function localSiderealTime(date, loc) {
  const gast = Astronomy.SiderealTime(Astronomy.MakeTime(date));
  return ((gast + loc.lon / 15) % 24 + 24) % 24;
}
function altAz(raHoursJ2000, decDegJ2000, date, loc) {
  const { raHours, decDeg } = precessToDate(raHoursJ2000, decDegJ2000, date);
  const lst = localSiderealTime(date, loc);
  const ha = ((lst - raHours) % 24 + 24) % 24;
  const H = ha * 15 * Math.PI / 180;
  const dec = decDeg * Math.PI / 180;
  const lat = loc.lat * Math.PI / 180;
  const sinAlt = Math.sin(dec) * Math.sin(lat) + Math.cos(dec) * Math.cos(lat) * Math.cos(H);
  const altDeg = Math.asin(Math.max(-1, Math.min(1, sinAlt))) * 180 / Math.PI;
  const az = Math.atan2(
    -Math.cos(dec) * Math.sin(H),
    Math.sin(dec) * Math.cos(lat) - Math.cos(dec) * Math.sin(lat) * Math.cos(H)
  ) * 180 / Math.PI;
  return { altDeg, azDeg: (az + 360) % 360, haHours: ha, lstHours: lst, raOfDate: raHours, decOfDate: decDeg };
}
function airmass(altDeg) {
  if (altDeg <= 0) return null;
  return 1 / Math.sin(altDeg * Math.PI / 180);
}
function helioCorrection(raHoursJ2000, decDegJ2000, date) {
  const time = Astronomy.MakeTime(date);
  const state = Astronomy.HelioState(Astronomy.Body.Earth, time);
  const s = unitVector(raHoursJ2000, decDegJ2000);
  const dotAu = state.x * s[0] + state.y * s[1] + state.z * s[2];
  const dotVel = state.vx * s[0] + state.vy * s[1] + state.vz * s[2];
  return {
    days: dotAu * LIGHT_TIME_AU_SEC / 86400,
    rvKmS: dotVel * AU_KM / 86400
  };
}
function instantInfo(raHoursJ2000, decDegJ2000, date, loc) {
  const pos = altAz(raHoursJ2000, decDegJ2000, date, loc);
  const jd = dateToJD(date);
  const hc = helioCorrection(raHoursJ2000, decDegJ2000, date);
  return {
    date,
    jd,
    jdHel: jd + hc.days,
    helCorrDays: hc.days,
    rvKmS: hc.rvKmS,
    lstHours: pos.lstHours,
    haHours: pos.haHours,
    altDeg: pos.altDeg,
    azDeg: pos.azDeg,
    airmass: airmass(pos.altDeg),
    raOfDate: pos.raOfDate,
    decOfDate: pos.decOfDate
  };
}
function nightInfo(isoDate, loc, sunAltDeg = -18) {
  const observer = observerOf(loc);
  const noonLocal = utcDate(isoDate, 12 - loc.lon / 15);
  let start = null;
  let end = null;
  try {
    const s = Astronomy.SearchAltitude(Astronomy.Body.Sun, observer, -1, noonLocal, 1, sunAltDeg);
    start = s ? s.date : null;
    const e = Astronomy.SearchAltitude(
      Astronomy.Body.Sun,
      observer,
      1,
      start ?? noonLocal,
      1,
      sunAltDeg
    );
    end = e ? e.date : null;
  } catch {
    start = null;
    end = null;
  }
  const midnight = utcDate(isoDate, 24 - loc.lon / 15);
  let moonRise = null;
  let moonSet = null;
  try {
    const r = Astronomy.SearchRiseSet(Astronomy.Body.Moon, observer, 1, noonLocal, 1);
    moonRise = r ? r.date : null;
    const st = Astronomy.SearchRiseSet(Astronomy.Body.Moon, observer, -1, noonLocal, 1);
    moonSet = st ? st.date : null;
  } catch {
  }
  const illum = Astronomy.Illumination(Astronomy.Body.Moon, midnight);
  return {
    isoDate,
    start,
    end,
    moonRise,
    moonSet,
    moonPhasePercent: illum.phase_fraction * 100,
    moonPhaseAngle: Astronomy.MoonPhase(midnight)
  };
}
function moonAltitude(date, loc) {
  const time = Astronomy.MakeTime(date);
  const observer = observerOf(loc);
  const eq = Astronomy.Equator(Astronomy.Body.Moon, time, observer, true, true);
  const hor = Astronomy.Horizon(time, observer, eq.ra, eq.dec, "normal");
  return hor.altitude;
}
function twilightTimes(isoDate, loc) {
  const observer = observerOf(loc);
  const noonLocal = utcDate(isoDate, 12 - loc.lon / 15);
  const search = (dir, altDeg, start) => {
    try {
      const r = Astronomy.SearchAltitude(Astronomy.Body.Sun, observer, dir, start, 1, altDeg);
      return r ? r.date : null;
    } catch {
      return null;
    }
  };
  const sunset = search(-1, 0, noonLocal);
  const civilDusk = search(-1, -6, sunset ?? noonLocal);
  const nauticalDusk = search(-1, -12, civilDusk ?? noonLocal);
  const astroDusk = search(-1, -18, nauticalDusk ?? noonLocal);
  const astroDawn = search(1, -18, astroDusk ?? noonLocal);
  const nauticalDawn = search(1, -12, astroDawn ?? noonLocal);
  const civilDawn = search(1, -6, nauticalDawn ?? noonLocal);
  const sunrise = search(1, 0, civilDawn ?? noonLocal);
  return { sunset, civilDusk, nauticalDusk, astroDusk, astroDawn, nauticalDawn, civilDawn, sunrise };
}
function observabilityWindows(raHours, decDeg, night, loc, minAltDeg = DEFAULT_MIN_ALTITUDE) {
  if (!night.start || !night.end) return [];
  const step = 6e4;
  const out = [];
  let openFrom = null;
  for (let t = night.start.getTime(); t <= night.end.getTime(); t += step) {
    const d = new Date(t);
    const above = altAz(raHours, decDeg, d, loc).altDeg >= minAltDeg;
    if (above && !openFrom) openFrom = d;
    if (!above && openFrom) {
      out.push({ from: openFrom, to: new Date(t - step) });
      openFrom = null;
    }
  }
  if (openFrom) out.push({ from: openFrom, to: night.end });
  return out;
}
function minimaInRange(target, fromIso, toIso, loc, minAltDeg = DEFAULT_MIN_ALTITUDE, onlyObservable = true) {
  const { epochJd, periodDays } = target;
  if (!periodDays || periodDays <= 0) return [];
  const jdFrom = dateToJD(utcDate(fromIso, 0));
  const jdTo = dateToJD(utcDate(toIso, 24));
  const eStart = Math.ceil((jdFrom - epochJd) / periodDays);
  const eEnd = Math.floor((jdTo - epochJd) / periodDays);
  if (eEnd - eStart > 2e5) return [];
  const nights = /* @__PURE__ */ new Map();
  const nightFor = (d) => {
    const localHours = d.getUTCHours() + d.getUTCMinutes() / 60 + loc.lon / 15;
    const anchor = new Date(d.getTime());
    if (localHours < 12) anchor.setUTCDate(anchor.getUTCDate() - 1);
    const iso2 = toIsoDate(anchor);
    let n = nights.get(iso2);
    if (!n) {
      n = nightInfo(iso2, loc);
      nights.set(iso2, n);
    }
    return n;
  };
  const out = [];
  for (let e = eStart; e <= eEnd; e++) {
    const jd = epochJd + e * periodDays;
    const date = jdToDate(jd);
    const info = instantInfo(target.raHours, target.decDeg, date, loc);
    const night = nightFor(date);
    const duringNight = !!night.start && !!night.end && date >= night.start && date <= night.end;
    const aboveMinAlt = info.altDeg >= minAltDeg;
    if (onlyObservable && !(duringNight && aboveMinAlt)) continue;
    out.push({
      epoch: e,
      jd,
      jdHel: info.jdHel,
      helCorrDays: info.helCorrDays,
      date,
      altDeg: info.altDeg,
      airmass: info.airmass,
      duringNight,
      aboveMinAlt
    });
  }
  return out;
}
function heliocentricPhase(date, target) {
  if (!target.epochJd || !target.periodDays || target.periodDays <= 0) return null;
  const jd = dateToJD(date);
  const jdHel = jd + helioCorrection(target.raHours, target.decDeg, date).days;
  const p = (jdHel - target.epochJd) / target.periodDays % 1;
  return p < 0 ? p + 1 : p;
}
function buildJournal(target, fromIso, toIso, loc, minAltDeg = DEFAULT_MIN_ALTITUDE, maxNights = 400) {
  const rows = [];
  let cur = utcDate(fromIso, 0);
  const end = utcDate(toIso, 0);
  while (cur <= end && rows.length < maxNights) {
    const iso2 = toIsoDate(cur);
    const night = nightInfo(iso2, loc);
    const windows = observabilityWindows(target.raHours, target.decDeg, night, loc, minAltDeg);
    let altMax = -90;
    if (night.start && night.end) {
      for (let t = night.start.getTime(); t <= night.end.getTime(); t += 10 * 6e4) {
        const a = altAz(target.raHours, target.decDeg, new Date(t), loc).altDeg;
        if (a > altMax) altMax = a;
      }
    }
    rows.push({
      isoDate: iso2,
      weekday: cur.getUTCDay(),
      jdMidnight: dateToJD(utcDate(iso2, 0)),
      night,
      windows,
      phaseFrom: windows[0] ? heliocentricPhase(windows[0].from, target) : null,
      phaseTo: windows[0] ? heliocentricPhase(windows[0].to, target) : null,
      altMax
    });
    cur = new Date(cur.getTime() + 864e5);
  }
  return rows;
}

// src/lib/mcp/helpers.ts
function ok(payload, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
var MIN_ALT_DEFAULT = DEFAULT_MIN_ALTITUDE;
var LOCATION_KEYS = POZOR_LOCATIONS.map((l) => l.key);
function resolveLocation(input) {
  if (typeof input.lat === "number" && typeof input.lon === "number") {
    return {
      key: "custom",
      label: "Custom",
      lat: input.lat,
      lon: input.lon,
      elevation: input.elevation ?? 0
    };
  }
  return getLocation(input.location ?? "");
}
var iso = (d) => d ? d.toISOString() : null;

// src/lib/mcp/tools/get-session.ts
var get_session_default = defineTool6({
  name: "get_session",
  title: "Get session with observations",
  description: "Read one observing session together with all of its observations, including the computed Argelander magnitude for each row.",
  inputSchema: { session_id: z6.string().uuid().describe("Session id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: session, error } = await supabase.from("sessions").select("id,name,observed_at_utc,jd,notes,is_favorite").eq("id", session_id).maybeSingle();
    if (error) return fail(error.message);
    if (!session) return fail("Session not found.");
    const { data: obs, error: obsErr } = await supabase.from("observations").select("id,row_index,ut_time,a,b,pasos_a,pasos_b,limit_value,note,star_id,stars(name,constellation,vsnet_code,aavso_code,chart_id)").eq("session_id", session_id).order("row_index");
    if (obsErr) return fail(obsErr.message);
    const observations = (obs ?? []).map((o) => {
      const star = o.stars;
      return { ...o, magnitude: computeMagnitude(o, star?.name).value };
    });
    return ok({ session, observations }, { session, observations });
  }
});

// src/lib/mcp/tools/update-session.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var update_session_default = defineTool7({
  name: "update_session",
  title: "Update observing session",
  description: "Rename an observing session or change its notes, UTC date/time or favourite flag.",
  inputSchema: {
    session_id: z7.string().uuid().describe("Session id."),
    name: z7.string().trim().max(200).optional().describe("New session name."),
    notes: z7.string().trim().max(2e3).optional().describe("New session notes."),
    observed_at_utc: z7.string().trim().optional().describe("New observation date/time in UTC ISO format."),
    is_favorite: z7.boolean().optional().describe("Mark or unmark as favourite.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ session_id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const fields = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(fields).length === 0) return fail("Nothing to update.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").update(fields).eq("id", session_id).select("id,name,observed_at_utc,jd,notes,is_favorite").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Session not found.");
    return ok(data, { session: data });
  }
});

// src/lib/mcp/tools/delete-session.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var delete_session_default = defineTool8({
  name: "delete_session",
  title: "Delete observing session",
  description: "Permanently delete an observing session and all observations that belong to it.",
  inputSchema: { session_id: z8.string().uuid().describe("Session id to delete.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { error: obsErr } = await supabase.from("observations").delete().eq("session_id", session_id);
    if (obsErr) return fail(obsErr.message);
    const { error } = await supabase.from("sessions").delete().eq("id", session_id);
    if (error) return fail(error.message);
    return ok({ deleted: session_id }, { deleted: session_id });
  }
});

// src/lib/mcp/tools/add-observation.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.25.76";
var add_observation_default = defineTool9({
  name: "add_observation",
  title: "Add observation",
  description: "Add an observation row to a session. Identify the star either by id or by catalog name; comparison values A/B accept magnitudes or comparator letters.",
  inputSchema: {
    session_id: z9.string().uuid().describe("Session the observation belongs to."),
    star_id: z9.string().uuid().optional().describe("Catalog star id."),
    star_name: z9.string().trim().min(1).optional().describe("Catalog star name (used when star_id is omitted)."),
    a: z9.string().trim().optional().describe("Brighter comparison star (magnitude or comparator letter)."),
    b: z9.string().trim().optional().describe("Fainter comparison star (magnitude or comparator letter)."),
    pasos_a: z9.number().int().min(0).max(99).optional().describe("Argelander steps to A."),
    pasos_b: z9.number().int().min(0).max(99).optional().describe("Argelander steps to B."),
    limit_value: z9.string().trim().optional().describe("Fainter-than limit, e.g. '<14.2'."),
    ut_time: z9.string().trim().optional().describe("UT time as HH:MM."),
    note: z9.string().trim().max(500).optional().describe("Row note, e.g. OUTBURST.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ session_id, star_id, star_name, ...row }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let starId = star_id ?? null;
    let resolvedName = star_name ?? null;
    if (!starId) {
      if (!star_name) return fail("Provide star_id or star_name.");
      const { data: matches, error: error2 } = await supabase.from("stars").select("id,name").ilike("name", star_name).limit(5);
      if (error2) return fail(error2.message);
      if (!matches || matches.length === 0) return fail(`Star '${star_name}' not found in the catalog.`);
      if (matches.length > 1) return fail(`Ambiguous star name: ${matches.map((m) => m.name).join(", ")}`);
      starId = matches[0].id;
      resolvedName = matches[0].name;
    }
    const { data: last } = await supabase.from("observations").select("row_index").eq("session_id", session_id).order("row_index", { ascending: false }).limit(1);
    const rowIndex = (last?.[0]?.row_index ?? -1) + 1;
    const { data, error } = await supabase.from("observations").insert({
      session_id,
      star_id: starId,
      user_id: ctx.getUserId(),
      row_index: rowIndex,
      a: row.a ?? null,
      b: row.b ?? null,
      pasos_a: row.pasos_a ?? null,
      pasos_b: row.pasos_b ?? null,
      limit_value: row.limit_value ?? null,
      ut_time: row.ut_time ?? null,
      note: row.note ?? null
    }).select("id,session_id,star_id,row_index,a,b,pasos_a,pasos_b,limit_value,ut_time,note").single();
    if (error) return fail(error.message);
    const magnitude = computeMagnitude(data, resolvedName ?? void 0).value;
    return ok({ ...data, magnitude }, { observation: { ...data, magnitude } });
  }
});

// src/lib/mcp/tools/update-observation.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z10 } from "npm:zod@^3.25.76";
var update_observation_default = defineTool10({
  name: "update_observation",
  title: "Update observation",
  description: "Change the comparison stars, steps, limit, UT time or note of an existing observation row.",
  inputSchema: {
    observation_id: z10.string().uuid().describe("Observation id."),
    a: z10.string().trim().nullable().optional().describe("Brighter comparison star."),
    b: z10.string().trim().nullable().optional().describe("Fainter comparison star."),
    pasos_a: z10.number().int().min(0).max(99).nullable().optional().describe("Argelander steps to A."),
    pasos_b: z10.number().int().min(0).max(99).nullable().optional().describe("Argelander steps to B."),
    limit_value: z10.string().trim().nullable().optional().describe("Fainter-than limit."),
    ut_time: z10.string().trim().nullable().optional().describe("UT time as HH:MM."),
    note: z10.string().trim().max(500).nullable().optional().describe("Row note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ observation_id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const fields = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(fields).length === 0) return fail("Nothing to update.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("observations").update(fields).eq("id", observation_id).select("id,session_id,star_id,row_index,a,b,pasos_a,pasos_b,limit_value,ut_time,note").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Observation not found.");
    return ok(data, { observation: data });
  }
});

// src/lib/mcp/tools/delete-observation.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z11 } from "npm:zod@^3.25.76";
var delete_observation_default = defineTool11({
  name: "delete_observation",
  title: "Delete observation",
  description: "Delete a single observation row from a session.",
  inputSchema: { observation_id: z11.string().uuid().describe("Observation id to delete.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ observation_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("observations").delete().eq("id", observation_id);
    if (error) return fail(error.message);
    return ok({ deleted: observation_id }, { deleted: observation_id });
  }
});

// src/lib/mcp/tools/export-session.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z12 } from "npm:zod@^3.25.76";

// src/lib/exporters/index.ts
function magOrLimit(r) {
  const m = computeMagnitude(r, r.star_name);
  return m.value == null ? null : csvSafe(m.value);
}
function csvSafe(s) {
  return s.replace(/[,\r\n]/g, " ").trim();
}
function rowDate(row, ctx) {
  if (!row.ut_time) return ctx.observedAt;
  const d = new Date(ctx.observedAt);
  applyUtTimeToDate(d, row.ut_time);
  return d;
}
function buildVSNET(rows, ctx) {
  const lines = [];
  for (const r of rows) {
    const mag = magOrLimit(r);
    if (!mag) continue;
    if (!r.vsnet_code) continue;
    const code = r.vsnet_code.trim().padEnd(8, " ");
    const dateStr = vsnetDate(rowDate(r, ctx));
    const rawNote = (r.note ?? "").trim();
    const suffix = rawNote ? ` ${rawNote}` : "";
    lines.push(`${code} ${dateStr} ${mag.padStart(5, " ")} ${ctx.obsCode}${suffix}`);
  }
  return lines.join("\n") + "\n";
}
function buildAAVSO(rows, ctx) {
  const header = [
    "#TYPE=Visual",
    `#OBSCODE=${ctx.obsCode}`,
    "#SOFTWARE=Visual-Astro (japysoft)",
    "#DELIM=,",
    "#DATE=JD",
    "#OBSTYPE=Visual"
  ].join("\n");
  const body = [];
  for (const r of rows) {
    const mag = magOrLimit(r);
    if (!mag) continue;
    if (!r.aavso_code) continue;
    const isLimit = !!(r.limit_value && r.limit_value.trim());
    const aVal = resolveCompValue(r.star_name, r.a ?? null);
    const bVal = resolveCompValue(r.star_name, r.b ?? null);
    const comp1 = isLimit ? Number.isFinite(bVal) ? bVal.toFixed(2) : csvSafe((r.limit_value ?? "").replace("<", "")) : Number.isFinite(aVal) ? aVal.toFixed(2) : csvSafe(r.a ?? "");
    const comp2 = isLimit ? "na" : Number.isFinite(bVal) ? bVal.toFixed(2) : csvSafe(r.b ?? "");
    const jd = ctx.jd + (rowDate(r, ctx).getTime() - ctx.observedAt.getTime()) / 864e5;
    const rawNote = csvSafe((r.note ?? "").trim().replace(/:/g, "Z"));
    const upper = rawNote.toUpperCase();
    const noteOut = upper === "OUTBURST" || upper === "ACTIVE" ? "Y" : rawNote || "na";
    body.push(
      [
        r.aavso_code,
        jd.toFixed(4),
        mag,
        "na",
        comp1 || "na",
        comp2 || "na",
        r.chart_id || "na",
        noteOut
      ].join(",")
    );
  }
  return header + "\n" + body.join("\n") + "\n";
}
function buildMEDUZA(rows, ctx) {
  const dateStr = meduzaDate(ctx.observedAt);
  const lines = ["Estrella,JD,Mag,Fecha UT,Obs,Estima"];
  for (const r of rows) {
    const mag = magOrLimit(r);
    if (!mag) continue;
    lines.push(
      [csvSafe(r.star_name), ctx.jd.toFixed(3), mag, dateStr, ctx.obsCode, csvSafe(aavsoEstima(r))].join(",")
    );
  }
  return lines.join("\n") + "\n";
}

// src/lib/mcp/tools/export-session.ts
var export_session_default = defineTool12({
  name: "export_session",
  title: "Export session",
  description: "Build the VSNET, AAVSO Visual or MEDUZA export text for a session, exactly as the app's export dialog does.",
  inputSchema: {
    session_id: z12.string().uuid().describe("Session to export."),
    format: z12.enum(["vsnet", "aavso", "meduza"]).describe("Export format."),
    obs_code: z12.string().trim().min(1).max(10).optional().describe("Observer code; defaults to the profile setting.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, format, obs_code }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: session, error } = await supabase.from("sessions").select("id,observed_at_utc,jd").eq("id", session_id).maybeSingle();
    if (error) return fail(error.message);
    if (!session) return fail("Session not found.");
    const { data: obs, error: obsErr } = await supabase.from("observations").select("a,b,pasos_a,pasos_b,limit_value,ut_time,note,row_index,stars(name,vsnet_code,aavso_code,chart_id)").eq("session_id", session_id).order("row_index");
    if (obsErr) return fail(obsErr.message);
    let code = obs_code?.trim();
    if (!code) {
      const { data: profile } = await supabase.from("profiles").select("obs_code").maybeSingle();
      code = profile?.obs_code ?? "DPV";
    }
    const observedAt = new Date(session.observed_at_utc);
    const rows = (obs ?? []).map((o) => {
      const star = o.stars;
      return {
        a: o.a,
        b: o.b,
        pasos_a: o.pasos_a,
        pasos_b: o.pasos_b,
        limit_value: o.limit_value,
        ut_time: o.ut_time,
        note: o.note,
        star_name: star?.name ?? "",
        vsnet_code: star?.vsnet_code ?? null,
        aavso_code: star?.aavso_code ?? null,
        chart_id: star?.chart_id ?? null
      };
    });
    const exportCtx = {
      observedAt,
      jd: session.jd != null ? Number(session.jd) : dateToJD(observedAt),
      obsCode: code
    };
    const text = format === "vsnet" ? buildVSNET(rows, exportCtx) : format === "aavso" ? buildAAVSO(rows, exportCtx) : buildMEDUZA(rows, exportCtx);
    return {
      content: [{ type: "text", text }],
      structuredContent: { format, obs_code: code, rows: rows.length, text }
    };
  }
});

// src/lib/mcp/tools/create-star.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z13 } from "npm:zod@^3.25.76";
var create_star_default = defineTool13({
  name: "create_star",
  title: "Add catalog star",
  description: "Add a star to the observer's visual catalog.",
  inputSchema: {
    name: z13.string().trim().min(1).max(120).describe("Star name, e.g. 'SS Cyg'."),
    constellation: z13.string().trim().min(1).max(20).describe("Constellation code, e.g. 'Cyg'."),
    type: z13.enum(["VISUAL", "BINAR", "ECL faint", "ECL bright"]).default("VISUAL").describe("Star type."),
    vsnet_code: z13.string().trim().max(20).optional().describe("VSNET code."),
    aavso_code: z13.string().trim().max(20).optional().describe("AAVSO designation."),
    chart_id: z13.string().trim().max(40).optional().describe("AAVSO chart id."),
    notes: z13.string().trim().max(1e3).optional().describe("Notes."),
    sort_order: z13.number().int().min(0).optional().describe("Position within the constellation.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let sortOrder = input.sort_order;
    if (sortOrder === void 0) {
      const { data: last } = await supabase.from("stars").select("sort_order").eq("constellation", input.constellation).order("sort_order", { ascending: false }).limit(1);
      sortOrder = (last?.[0]?.sort_order ?? -1) + 1;
    }
    const { data, error } = await supabase.from("stars").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      constellation: input.constellation,
      type: input.type ?? "VISUAL",
      vsnet_code: input.vsnet_code ?? null,
      aavso_code: input.aavso_code ?? null,
      chart_id: input.chart_id ?? null,
      notes: input.notes ?? null,
      sort_order: sortOrder
    }).select("id,name,constellation,type,vsnet_code,aavso_code,chart_id,notes,sort_order").single();
    if (error) return fail(error.message);
    return ok(data, { star: data });
  }
});

// src/lib/mcp/tools/update-star.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z14 } from "npm:zod@^3.25.76";
var update_star_default = defineTool14({
  name: "update_star",
  title: "Update catalog star",
  description: "Edit a star in the visual catalog, including its display order inside the constellation.",
  inputSchema: {
    star_id: z14.string().uuid().describe("Star id."),
    name: z14.string().trim().min(1).max(120).optional().describe("Star name."),
    constellation: z14.string().trim().min(1).max(20).optional().describe("Constellation code."),
    type: z14.enum(["VISUAL", "BINAR", "ECL faint", "ECL bright"]).optional().describe("Star type."),
    vsnet_code: z14.string().trim().nullable().optional().describe("VSNET code."),
    aavso_code: z14.string().trim().nullable().optional().describe("AAVSO designation."),
    chart_id: z14.string().trim().nullable().optional().describe("AAVSO chart id."),
    notes: z14.string().trim().nullable().optional().describe("Notes."),
    sort_order: z14.number().int().min(0).optional().describe("Position within the constellation.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ star_id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const fields = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(fields).length === 0) return fail("Nothing to update.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("stars").update(fields).eq("id", star_id).select("id,name,constellation,type,vsnet_code,aavso_code,chart_id,notes,sort_order").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Star not found.");
    return ok(data, { star: data });
  }
});

// src/lib/mcp/tools/delete-star.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z15 } from "npm:zod@^3.25.76";
var delete_star_default = defineTool15({
  name: "delete_star",
  title: "Delete catalog star",
  description: "Remove a star from the visual catalog. Fails if observations still reference it.",
  inputSchema: { star_id: z15.string().uuid().describe("Star id to delete.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ star_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("stars").delete().eq("id", star_id);
    if (error) return fail(error.message);
    return ok({ deleted: star_id }, { deleted: star_id });
  }
});

// src/lib/mcp/tools/list-ccd-catalogs.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_ccd_catalogs_default = defineTool16({
  name: "list_ccd_catalogs",
  title: "List POZOR catalogs",
  description: "List the observer's POZOR CCD target catalogs (groups of targets).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ccd_catalogs").select("id,name,sort_order,created_at").order("sort_order");
    if (error) return fail(error.message);
    return ok(data ?? [], { catalogs: data ?? [] });
  }
});

// src/lib/mcp/tools/create-ccd-target.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z16 } from "npm:zod@^3.25.76";
var create_ccd_target_default = defineTool17({
  name: "create_ccd_target",
  title: "Add POZOR CCD target",
  description: "Add a CCD/photometry target to a POZOR catalog. Coordinates are J2000 (RA in hours, Dec in degrees).",
  inputSchema: {
    name: z16.string().trim().min(1).max(120).describe("Target name."),
    ra_hours: z16.number().min(0).max(24).describe("J2000 right ascension in hours."),
    dec_deg: z16.number().min(-90).max(90).describe("J2000 declination in degrees."),
    constellation: z16.string().trim().max(20).optional().describe("Constellation code."),
    catalog_id: z16.string().uuid().optional().describe("Target catalog id; defaults to the first catalog."),
    catalog_name: z16.string().trim().min(1).max(120).optional().describe("Catalog name; created if it does not exist."),
    epoch_jd: z16.number().optional().describe("Epoch of primary minimum (JD)."),
    period_days: z16.number().positive().optional().describe("Orbital/pulsation period in days."),
    filters: z16.string().trim().max(60).optional().describe("Filters used, e.g. 'V, R'."),
    notes: z16.string().trim().max(1e3).optional().describe("Notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let catalogId = input.catalog_id ?? null;
    if (!catalogId) {
      const { data: cats, error: catErr } = await supabase.from("ccd_catalogs").select("id,name").order("sort_order");
      if (catErr) return fail(catErr.message);
      const wanted = input.catalog_name?.trim().toLowerCase();
      const found = wanted ? cats?.find((c) => c.name.toLowerCase() === wanted) : cats?.[0];
      if (found) catalogId = found.id;
      else {
        const { data: created, error: createErr } = await supabase.from("ccd_catalogs").insert({ user_id: ctx.getUserId(), name: input.catalog_name?.trim() || "POZOR", sort_order: cats?.length ?? 0 }).select("id").single();
        if (createErr) return fail(createErr.message);
        catalogId = created.id;
      }
    }
    const { data, error } = await supabase.from("ccd_targets").insert({
      user_id: ctx.getUserId(),
      catalog_id: catalogId,
      name: input.name,
      constellation: input.constellation ?? "",
      ra_hours: input.ra_hours,
      dec_deg: input.dec_deg,
      epoch_jd: input.epoch_jd ?? null,
      period_days: input.period_days ?? null,
      filters: input.filters ?? null,
      notes: input.notes ?? null
    }).select("id,catalog_id,name,constellation,ra_hours,dec_deg,epoch_jd,period_days,filters,notes").single();
    if (error) return fail(error.message);
    return ok(data, { target: data });
  }
});

// src/lib/mcp/tools/update-ccd-target.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z17 } from "npm:zod@^3.25.76";
var update_ccd_target_default = defineTool18({
  name: "update_ccd_target",
  title: "Update POZOR CCD target",
  description: "Edit a CCD/photometry target's coordinates, ephemeris, filters or notes.",
  inputSchema: {
    target_id: z17.string().uuid().describe("Target id."),
    name: z17.string().trim().min(1).max(120).optional().describe("Target name."),
    constellation: z17.string().trim().max(20).optional().describe("Constellation code."),
    ra_hours: z17.number().min(0).max(24).optional().describe("J2000 right ascension in hours."),
    dec_deg: z17.number().min(-90).max(90).optional().describe("J2000 declination in degrees."),
    epoch_jd: z17.number().nullable().optional().describe("Epoch of primary minimum (JD)."),
    period_days: z17.number().positive().nullable().optional().describe("Period in days."),
    filters: z17.string().trim().nullable().optional().describe("Filters used."),
    notes: z17.string().trim().nullable().optional().describe("Notes."),
    sort_order: z17.number().int().min(0).optional().describe("Position within the catalog.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ target_id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const fields = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(fields).length === 0) return fail("Nothing to update.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ccd_targets").update(fields).eq("id", target_id).select("id,catalog_id,name,constellation,ra_hours,dec_deg,epoch_jd,period_days,filters,notes,sort_order").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Target not found.");
    return ok(data, { target: data });
  }
});

// src/lib/mcp/tools/delete-ccd-target.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z18 } from "npm:zod@^3.25.76";
var delete_ccd_target_default = defineTool19({
  name: "delete_ccd_target",
  title: "Delete POZOR CCD target",
  description: "Remove a CCD/photometry target from a POZOR catalog.",
  inputSchema: { target_id: z18.string().uuid().describe("Target id to delete.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ target_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("ccd_targets").delete().eq("id", target_id);
    if (error) return fail(error.message);
    return ok({ deleted: target_id }, { deleted: target_id });
  }
});

// src/lib/mcp/tools/pozor-night.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z19 } from "npm:zod@^3.25.76";
import * as Astronomy2 from "npm:astronomy-engine@^2.1.19";
var pozor_night_default = defineTool20({
  name: "pozor_night",
  title: "POZOR night conditions",
  description: "Astronomical night boundaries, twilight times, Moon phase/illumination and Moon altitude for a given date and observing site.",
  inputSchema: {
    date: z19.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Evening date of the night, YYYY-MM-DD (UTC)."),
    location: z19.string().trim().optional().describe(`Site key: ${LOCATION_KEYS.join(", ")}.`),
    lat: z19.number().min(-90).max(90).optional().describe("Custom latitude (degrees north)."),
    lon: z19.number().min(-180).max(180).optional().describe("Custom longitude (degrees east)."),
    elevation: z19.number().optional().describe("Custom elevation in metres.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, ...loc }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const site = resolveLocation(loc);
    const night = nightInfo(date, site);
    const tw = twilightTimes(date, site);
    const mid = night.start && night.end ? new Date((night.start.getTime() + night.end.getTime()) / 2) : utcDate(date, 0);
    const illum = Astronomy2.Illumination(Astronomy2.Body.Moon, mid);
    const payload = {
      date,
      site: { key: site.key, label: site.label, lat: site.lat, lon: site.lon, elevation: site.elevation },
      night: {
        start: iso(night.start),
        end: iso(night.end),
        durationHours: night.start && night.end ? Number(((night.end.getTime() - night.start.getTime()) / 36e5).toFixed(3)) : null,
        moonRise: iso(night.moonRise),
        moonSet: iso(night.moonSet),
        moonPhasePercent: night.moonPhasePercent
      },
      twilight: {
        sunset: iso(tw.sunset),
        civilDusk: iso(tw.civilDusk),
        nauticalDusk: iso(tw.nauticalDusk),
        astroDusk: iso(tw.astroDusk),
        astroDawn: iso(tw.astroDawn),
        nauticalDawn: iso(tw.nauticalDawn),
        civilDawn: iso(tw.civilDawn),
        sunrise: iso(tw.sunrise)
      },
      moon: {
        atUtc: iso(mid),
        phaseAngleDeg: illum.phase_angle,
        illuminatedFraction: illum.phase_fraction,
        altitudeDeg: Number(moonAltitude(mid, site).toFixed(2))
      }
    };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/pozor-instant.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z20 } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/pozor-target.ts
async function resolveTarget(ctx, input) {
  if (typeof input.ra_hours === "number" && typeof input.dec_deg === "number") {
    return {
      target: {
        name: input.target_name ?? "custom",
        raHours: input.ra_hours,
        decDeg: input.dec_deg,
        epochJd: input.epoch_jd ?? null,
        periodDays: input.period_days ?? null
      }
    };
  }
  if (!input.target_id && !input.target_name) {
    return { error: "Provide target_id, target_name, or ra_hours + dec_deg." };
  }
  const supabase = supabaseForUser(ctx);
  let query = supabase.from("ccd_targets").select("id,name,ra_hours,dec_deg,epoch_jd,period_days").limit(5);
  query = input.target_id ? query.eq("id", input.target_id) : query.ilike("name", `%${input.target_name}%`);
  const { data, error } = await query;
  if (error) return { error: error.message };
  if (!data || data.length === 0) return { error: "CCD target not found." };
  if (data.length > 1) return { error: `Ambiguous target: ${data.map((d) => d.name).join(", ")}` };
  const row = data[0];
  return {
    target: {
      name: row.name,
      raHours: Number(row.ra_hours),
      decDeg: Number(row.dec_deg),
      epochJd: input.epoch_jd ?? (row.epoch_jd != null ? Number(row.epoch_jd) : null),
      periodDays: input.period_days ?? (row.period_days != null ? Number(row.period_days) : null)
    }
  };
}

// src/lib/mcp/tools/pozor-instant.ts
var pozor_instant_default = defineTool21({
  name: "pozor_instant",
  title: "POZOR position at an instant",
  description: "Altitude, azimuth, hour angle, airmass, precessed coordinates, heliocentric JD correction and eclipsing phase for a target at a given UTC instant.",
  inputSchema: {
    datetime_utc: z20.string().trim().describe("UTC instant in ISO format, e.g. 2026-08-01T22:30:00Z."),
    target_id: z20.string().uuid().optional().describe("CCD catalog target id."),
    target_name: z20.string().trim().min(1).optional().describe("CCD catalog target name."),
    ra_hours: z20.number().min(0).max(24).optional().describe("J2000 RA in hours (instead of a catalog target)."),
    dec_deg: z20.number().min(-90).max(90).optional().describe("J2000 Dec in degrees."),
    epoch_jd: z20.number().optional().describe("Epoch of minimum (JD) for phase."),
    period_days: z20.number().positive().optional().describe("Period in days for phase."),
    location: z20.string().trim().optional().describe(`Site key: ${LOCATION_KEYS.join(", ")}.`),
    lat: z20.number().min(-90).max(90).optional().describe("Custom latitude."),
    lon: z20.number().min(-180).max(180).optional().describe("Custom longitude."),
    elevation: z20.number().optional().describe("Custom elevation in metres.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { target, error } = await resolveTarget(ctx, input);
    if (error || !target) return fail(error ?? "Target not resolved.");
    const when = new Date(input.datetime_utc);
    if (Number.isNaN(when.getTime())) return fail("Invalid datetime_utc.");
    const site = resolveLocation(input);
    const info = instantInfo(target.raHours, target.decDeg, when, site);
    const payload = {
      target: { name: target.name, raHoursJ2000: target.raHours, decDegJ2000: target.decDeg },
      site: { key: site.key, label: site.label },
      atUtc: iso(when),
      raOfDate: formatHMS(info.raOfDate),
      decOfDate: formatDMS(info.decOfDate),
      altitudeDeg: Number(info.altDeg.toFixed(3)),
      azimuthDeg: Number(info.azDeg.toFixed(3)),
      hourAngleHours: Number(info.haHours.toFixed(4)),
      lstHours: Number(info.lstHours.toFixed(4)),
      airmass: info.airmass,
      jd: info.jd,
      jdHel: info.jdHel,
      helCorrDays: info.helCorrDays,
      phase: heliocentricPhase(when, target)
    };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/pozor-journal.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z21 } from "npm:zod@^3.25.76";
var pozor_journal_default = defineTool22({
  name: "pozor_journal",
  title: "POZOR observability journal",
  description: "Night-by-night observability windows for a target between two dates: when it is above the minimum altitude during astronomical night, plus maximum altitude and eclipsing phase at the window edges.",
  inputSchema: {
    from: z21.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).describe("First evening date, YYYY-MM-DD."),
    to: z21.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Last evening date, YYYY-MM-DD."),
    target_id: z21.string().uuid().optional().describe("CCD catalog target id."),
    target_name: z21.string().trim().min(1).optional().describe("CCD catalog target name."),
    ra_hours: z21.number().min(0).max(24).optional().describe("J2000 RA in hours."),
    dec_deg: z21.number().min(-90).max(90).optional().describe("J2000 Dec in degrees."),
    epoch_jd: z21.number().optional().describe("Epoch of minimum (JD)."),
    period_days: z21.number().positive().optional().describe("Period in days."),
    min_altitude: z21.number().min(0).max(90).default(MIN_ALT_DEFAULT).describe("Minimum usable altitude in degrees."),
    only_observable: z21.boolean().default(true).describe("Return only nights with at least one window."),
    location: z21.string().trim().optional().describe(`Site key: ${LOCATION_KEYS.join(", ")}.`),
    lat: z21.number().min(-90).max(90).optional().describe("Custom latitude."),
    lon: z21.number().min(-180).max(180).optional().describe("Custom longitude."),
    elevation: z21.number().optional().describe("Custom elevation in metres.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { target, error } = await resolveTarget(ctx, input);
    if (error || !target) return fail(error ?? "Target not resolved.");
    const site = resolveLocation(input);
    const minAlt = input.min_altitude ?? MIN_ALT_DEFAULT;
    const rows = buildJournal(target, input.from, input.to, site, minAlt).filter((r) => input.only_observable === false ? true : r.windows.length > 0).map((r) => ({
      date: r.isoDate,
      jdMidnight: r.jdMidnight,
      nightStart: iso(r.night.start),
      nightEnd: iso(r.night.end),
      maxAltitudeDeg: Number(r.altMax.toFixed(2)),
      phaseFrom: r.phaseFrom,
      phaseTo: r.phaseTo,
      windows: r.windows.map((w) => ({ from: iso(w.from), to: iso(w.to) }))
    }));
    const payload = {
      target: { name: target.name, raHoursJ2000: target.raHours, decDegJ2000: target.decDeg },
      site: { key: site.key, label: site.label },
      minAltitudeDeg: minAlt,
      nights: rows
    };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/pozor-minima.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z22 } from "npm:zod@^3.25.76";
var pozor_minima_default = defineTool23({
  name: "pozor_minima",
  title: "POZOR minima predictions",
  description: "Predicted minima of an eclipsing target in a date range, with geocentric and heliocentric JD, altitude, airmass and whether the minimum falls inside the observable night.",
  inputSchema: {
    from: z22.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Range start date, YYYY-MM-DD."),
    to: z22.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Range end date, YYYY-MM-DD."),
    target_id: z22.string().uuid().optional().describe("CCD catalog target id."),
    target_name: z22.string().trim().min(1).optional().describe("CCD catalog target name."),
    ra_hours: z22.number().min(0).max(24).optional().describe("J2000 RA in hours."),
    dec_deg: z22.number().min(-90).max(90).optional().describe("J2000 Dec in degrees."),
    epoch_jd: z22.number().optional().describe("Epoch of primary minimum (JD)."),
    period_days: z22.number().positive().optional().describe("Period in days."),
    min_altitude: z22.number().min(0).max(90).default(MIN_ALT_DEFAULT).describe("Minimum usable altitude in degrees."),
    only_observable: z22.boolean().default(true).describe("Keep only minima observable from the site."),
    location: z22.string().trim().optional().describe(`Site key: ${LOCATION_KEYS.join(", ")}.`),
    lat: z22.number().min(-90).max(90).optional().describe("Custom latitude."),
    lon: z22.number().min(-180).max(180).optional().describe("Custom longitude."),
    elevation: z22.number().optional().describe("Custom elevation in metres.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { target, error } = await resolveTarget(ctx, input);
    if (error || !target) return fail(error ?? "Target not resolved.");
    if (!target.epochJd || !target.periodDays) return fail("This target has no epoch/period ephemeris.");
    const site = resolveLocation(input);
    const minAlt = input.min_altitude ?? MIN_ALT_DEFAULT;
    const events = minimaInRange(
      { raHours: target.raHours, decDeg: target.decDeg, epochJd: target.epochJd, periodDays: target.periodDays },
      input.from,
      input.to,
      site,
      minAlt,
      input.only_observable !== false
    ).map((e) => ({
      epoch: e.epoch,
      utc: iso(e.date),
      jd: e.jd,
      jdHel: e.jdHel,
      helCorrDays: e.helCorrDays,
      altitudeDeg: Number(e.altDeg.toFixed(2)),
      airmass: e.airmass,
      duringNight: e.duringNight,
      aboveMinAltitude: e.aboveMinAlt
    }));
    const payload = {
      target: { name: target.name, epochJd: target.epochJd, periodDays: target.periodDays },
      site: { key: site.key, label: site.label },
      minAltitudeDeg: minAlt,
      minima: events
    };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/jd-convert.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z23 } from "npm:zod@^3.25.76";
var jd_convert_default = defineTool24({
  name: "jd_convert",
  title: "Julian Date converter",
  description: "Convert a UTC date/time to Julian Date, or a Julian Date back to UTC.",
  inputSchema: {
    jd: z23.number().optional().describe("Julian Date to convert to UTC."),
    datetime_utc: z23.string().trim().optional().describe("UTC ISO date/time to convert to Julian Date.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ jd, datetime_utc }) => {
    if (typeof jd === "number") {
      const d = jdToDate(jd);
      return ok({ jd, datetime_utc: d.toISOString() }, { jd, datetime_utc: d.toISOString() });
    }
    if (datetime_utc) {
      const d = new Date(datetime_utc);
      if (Number.isNaN(d.getTime())) return fail("Invalid datetime_utc.");
      const value = dateToJD(d);
      return ok({ jd: value, datetime_utc: d.toISOString() }, { jd: value, datetime_utc: d.toISOString() });
    }
    return fail("Provide jd or datetime_utc.");
  }
});

// src/lib/mcp/tools/convert-sips.ts
import { defineTool as defineTool25 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z24 } from "npm:zod@^3.25.76";

// src/lib/sips.ts
function sipsJdToDate(jd) {
  const J = jd + 0.5;
  const Z = Math.floor(J);
  const F = J - Z;
  let A = Z;
  if (Z >= 2299161) {
    const alpha = Math.floor((Z - 186721625e-2) / 36524.25);
    A = Z + 1 + alpha - Math.floor(alpha / 4);
  }
  const B = A + 1524;
  const C = Math.floor((B - 122.1) / 365.25);
  const D = Math.floor(365.25 * C);
  const E = Math.floor((B - D) / 30.6001);
  const dayF = B - D - Math.floor(30.6001 * E) + F;
  const day = Math.floor(dayF);
  const dayFrac = dayF - day;
  const month = E < 14 ? E - 1 : E - 13;
  const year = month > 2 ? C - 4716 : C - 4715;
  const totalSec = Math.round(dayFrac * 86400);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor(totalSec % 3600 / 60);
  const s = totalSec % 60;
  return new Date(Date.UTC(year, month - 1, day, h, m, s));
}
function vsnetDateFromJD(jd) {
  const d = sipsJdToDate(jd);
  const y = d.getUTCFullYear();
  const mo = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = d.getUTCDate();
  const frac = (d.getUTCHours() + d.getUTCMinutes() / 60 + d.getUTCSeconds() / 3600) / 24;
  const dayWithFrac = (day + frac).toFixed(3).padStart(6, "0");
  return `${y}${mo}${dayWithFrac}`;
}
function parseSIPS(text, msgs = {
  minCols: (n) => `Line ${n}: at least 2 columns required`,
  nonNumeric: (n) => `Line ${n}: non-numeric JD or magnitude`
}) {
  const rows = [];
  const errors = [];
  let varName = null;
  let filter = null;
  const lines = text.split(/\r?\n/);
  lines.forEach((raw, i) => {
    const line = raw.trim();
    if (!line) return;
    if (line.startsWith("#")) {
      const mVar = line.match(/VAR\s*Name\s*:\s*(.+?)\s*$/i);
      if (mVar) varName = mVar[1].trim();
      const mFil = line.match(/Filter\s*:\s*([^\s]+)/i);
      if (mFil) filter = mFil[1].trim();
      return;
    }
    const parts = line.split(/[\s,;]+/);
    if (parts.length < 2) {
      errors.push(msgs.minCols(i + 1));
      return;
    }
    const jd = parseFloat(parts[0]);
    const mag = parseFloat(parts[1]);
    const err = parts.length >= 3 ? parseFloat(parts[2]) : NaN;
    if (!Number.isFinite(jd) || !Number.isFinite(mag)) {
      errors.push(msgs.nonNumeric(i + 1));
      return;
    }
    rows.push({ jd, mag, err: Number.isFinite(err) ? err : 0 });
  });
  return { rows, varName, filter, errors };
}
function vsnetFilter(f) {
  if (!f) return "C";
  const key = f.toUpperCase();
  const map = {
    V: "V",
    B: "B",
    R: "R",
    I: "I",
    U: "U",
    TR: "TR",
    TG: "TG",
    TB: "TB",
    CV: "CV",
    CR: "CR",
    CBB: "CBB",
    LPR: "CV",
    CLEAR: "C",
    CLR: "C",
    NONE: "C"
  };
  return map[key] ?? key;
}
function buildVSNETFromSIPS(rows, starCode, obsCode, filter) {
  const code = starCode.trim().padEnd(8, " ");
  const obs = obsCode.trim();
  const filt = vsnetFilter(filter);
  const out = [];
  for (const r of rows) {
    const dateStr = vsnetDateFromJD(r.jd);
    const magStr = r.mag.toFixed(4).padStart(7, " ");
    out.push(`${code} ${dateStr} ${magStr} ${obs} ${filt}`);
  }
  return out.join("\n") + (out.length ? "\n" : "");
}
var AAVSO_FILTER_MAP = {
  V: "V",
  B: "B",
  R: "R",
  I: "I",
  U: "U",
  TR: "TR",
  TG: "TG",
  TB: "TB",
  CV: "CV",
  CR: "CR",
  CBB: "CBB",
  LPR: "CV",
  CLEAR: "CV",
  CLR: "CV",
  NONE: "CV"
};
function aavsoFilter(f) {
  if (!f) return "CV";
  const key = f.toUpperCase();
  return AAVSO_FILTER_MAP[key] ?? key;
}
function buildAAVSOFromSIPS(rows, aavsoCode, obsCode, filter, chartId) {
  const header = [
    "#TYPE=Extended",
    `#OBSCODE=${obsCode.trim()}`,
    "#SOFTWARE=Visual-Astro (japysoft)",
    "#DELIM=,",
    "#DATE=JD",
    "#OBSTYPE=CCD"
  ].join("\n");
  const filt = aavsoFilter(filter);
  const chart = chartId.trim() || "na";
  const body = [];
  for (const r of rows) {
    body.push([
      aavsoCode.trim(),
      r.jd.toFixed(6),
      r.mag.toFixed(4),
      r.err > 0 ? r.err.toFixed(4) : "na",
      filt,
      "NO",
      "STD",
      "ENSEMBLE",
      "na",
      "na",
      "na",
      "na",
      "na",
      chart,
      "na"
    ].join(","));
  }
  return header + "\n" + body.join("\n") + "\n";
}

// src/lib/mcp/tools/convert-sips.ts
var convert_sips_default = defineTool25({
  name: "convert_sips",
  title: "Convert SIPS Standard to VSNET/AAVSO",
  description: "Convert a SIPS Standard photometry file (JD, magnitude, error, with optional '#' header lines) into VSNET or AAVSO Extended CCD format.",
  inputSchema: {
    data: z24.string().min(1).describe("Raw SIPS Standard file content."),
    format: z24.enum(["vsnet", "aavso"]).describe("Output format."),
    star_code: z24.string().trim().min(1).max(40).describe("VSNET code or AAVSO designation of the star."),
    obs_code: z24.string().trim().max(10).optional().describe("Observer code; defaults to the profile setting."),
    filter: z24.string().trim().max(20).optional().describe("Override the filter detected in the file header."),
    chart_id: z24.string().trim().max(40).optional().describe("AAVSO chart id (AAVSO format only).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ data, format, star_code, obs_code, filter, chart_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const parsed = parseSIPS(data);
    if (parsed.rows.length === 0) return fail(`No usable rows. ${parsed.errors.slice(0, 5).join("; ")}`);
    let code = obs_code?.trim();
    if (!code) {
      const supabase = supabaseForUser(ctx);
      const { data: profile } = await supabase.from("profiles").select("obs_code").maybeSingle();
      code = profile?.obs_code ?? "DPV";
    }
    const filt = filter?.trim() || parsed.filter;
    const text = format === "vsnet" ? buildVSNETFromSIPS(parsed.rows, star_code, code, filt) : buildAAVSOFromSIPS(parsed.rows, star_code, code, filt, chart_id ?? "");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        format,
        rows: parsed.rows.length,
        detectedStar: parsed.varName,
        filter: filt,
        warnings: parsed.errors,
        text
      }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool26 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_profile_default = defineTool26({
  name: "get_profile",
  title: "Get observer profile",
  description: "Read the signed-in observer's profile: observer code, reference date, export portal preferences, plan status and counts of sessions, stars and CCD targets.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: profile, error } = await supabase.from("profiles").select("obs_code,fecha_referencia,open_portal_after_export,portal_urls").maybeSingle();
    if (error) return fail(error.message);
    const counts = await Promise.all(
      ["sessions", "observations", "stars", "ccd_targets"].map(async (table) => {
        const { count } = await supabase.from(table).select("id", { count: "exact", head: true });
        return [table, count ?? 0];
      })
    );
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      profile: profile ?? null,
      counts: Object.fromEntries(counts)
    };
    return ok(payload, payload);
  }
});

// src/lib/mcp/tools/update-profile.ts
import { defineTool as defineTool27 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z25 } from "npm:zod@^3.25.76";
var update_profile_default = defineTool27({
  name: "update_profile",
  title: "Update observer profile",
  description: "Change the observer code or reference date used by exports.",
  inputSchema: {
    obs_code: z25.string().trim().min(1).max(10).optional().describe("Observer code, e.g. 'DPV'."),
    fecha_referencia: z25.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Reference date, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (patch, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const fields = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(fields).length === 0) return fail("Nothing to update.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").update(fields).eq("user_id", ctx.getUserId()).select("obs_code,fecha_referencia").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Profile not found.");
    return ok(data, { profile: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "tbmyxbratepxomskzzsq";
var mcp_default = defineMcp({
  name: "visual-astro",
  title: "Visual Astro",
  version: "0.1.0",
  instructions: "Full toolset for Visual Astro, a variable-star observing logbook. Read and edit observing sessions and their observations (with computed Argelander magnitudes), manage the visual star catalog, manage POZOR CCD/photometry catalogs and targets, run POZOR observability computations (night conditions, altitude/airmass at an instant, night-by-night journals, minima predictions), build VSNET/AAVSO/MEDUZA exports, convert SIPS Standard photometry files and Julian Dates, and read or update the observer profile. All data is scoped to the signed-in observer.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    update_profile_default,
    list_sessions_default,
    get_session_default,
    create_session_default,
    update_session_default,
    delete_session_default,
    list_observations_default,
    add_observation_default,
    update_observation_default,
    delete_observation_default,
    export_session_default,
    list_stars_default,
    create_star_default,
    update_star_default,
    delete_star_default,
    list_ccd_catalogs_default,
    list_ccd_targets_default,
    create_ccd_target_default,
    update_ccd_target_default,
    delete_ccd_target_default,
    pozor_night_default,
    pozor_instant_default,
    pozor_journal_default,
    pozor_minima_default,
    jd_convert_default,
    convert_sips_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
